# Generated by Django 5.1.1 on 2024-11-19 19:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_user_lattitude_remove_user_longitude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
    ]
