# Generated by Django 4.2.16 on 2024-11-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0002_alter_driver_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="driver",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="driver",
            name="is_profile_complete",
            field=models.BooleanField(default=False),
        ),
    ]
