# Generated by Django 4.2.16 on 2024-11-19 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0003_driver_is_active_driver_is_approved_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="driver",
            old_name="is_approved",
            new_name="is_banned",
        ),
        migrations.AddField(
            model_name="driver",
            name="ban_reason",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name="DriverApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("can_reapply", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application",
                        to="drivers.driver",
                    ),
                ),
            ],
        ),
    ]
