# Generated by Django 4.2.16 on 2024-11-27 17:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0004_rename_is_approved_driver_is_banned_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DriverApplication",
        ),
    ]
