# Generated by Django 4.2.16 on 2024-11-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0006_remove_driver_driver_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="ban_reason",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
