# Generated by Django 4.2.16 on 2024-11-28 14:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="arrival_location",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name="ride",
            name="departure_location",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
