# Generated by Django 4.2.16 on 2024-11-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0002_alter_ride_arrival_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
