# Generated by Django 4.2.16 on 2024-11-19 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0002_alter_driver_user"),
        ("vehicles", "0002_alter_vehicle_driver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="driver",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicle",
                to="drivers.driver",
            ),
        ),
    ]
