# Generated by Django 4.2.16 on 2024-11-28 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0001_initial"),
        ("trip_preferences", "0002_driverpreference"),
    ]

    operations = [
        migrations.CreateModel(
            name="RidePreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "preference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_preferences",
                        to="trip_preferences.trippreferences",
                    ),
                ),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="rides.ride",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DriverPreference",
        ),
    ]
